# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.btnPrb1 = QtWidgets.QPushButton(Form)
        self.btnPrb1.setEnabled(True)
        self.btnPrb1.setGeometry(QtCore.QRect(235, 210, 230, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Cond")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnPrb1.setFont(font)
        self.btnPrb1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnPrb1.setObjectName("btnPrb1")
        self.btnPrb2 = QtWidgets.QPushButton(Form)
        self.btnPrb2.setEnabled(True)
        self.btnPrb2.setGeometry(QtCore.QRect(235, 320, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Cond")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnPrb2.setFont(font)
        self.btnPrb2.setObjectName("btnPrb2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(235, 90, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnPrb1.setText(_translate("Form", "Problem 1"))
        self.btnPrb2.setText(_translate("Form", "Problem 2"))
        self.label.setText(_translate("Form", "KOU YazLab 1.3"))
        self.label_2.setText(_translate("Form", "Restoran Yönetim Sistemi"))
